### PR TITLE
Support local and CI tests

### PR DESCRIPTION
**Pull request by lippserd**

### CODE REVIEW

**Comment by Thomas-Gelf** [comment]
@lippserd, this change:
* now downloads 30 packages for a simple `composer install`
* it's no longer possible to just run `phpunit` on your Linux system,  you're stuck with `composer test` and hard-coded properties
* Xenial ships phpunit v5.1, Stretch v5.4

This way, running tests on a system in a customer datacenter with no internet access is impossible. Was breaking this intentional or by accident?

Cheers,
Thomas

**Comment by lippserd** [comment]
Hi Tom,

If you don't want those packages, just run composer with --no-dev. Travis CI still does that. For development I want to have those packages instead of just the phars. Why should it be no longer possible to just run phpunit?

Best,
Eric

**Comment by Thomas-Gelf** [comment]
Blind guess: it fails because of missing compat layer. Quick test with `phpunit` as shipped by Xenial:

```
user@web1:~/ipl-stdlib# phpunit
PHPUnit 5.1.3 by Sebastian Bergmann and contributors.

Time: 14 ms, Memory: 4.00MB

No tests executed!
```

Works fine with a dated `phpunit.phar` (6.0.x) on the very same system.

> For development I want to have those packages instead of just the phars.

I've been there before. Had this in a few repos, removed it everywhere. I could live with these "two" dependencies, but honestly: I started to hate them. I'm often working in Hotels with slow internet and simply wasted too much time by just waiting. I don't really get the advantage of throwing in 30 dependencies over using a single phar. Download alone takes easily 30 times as long for the "composer way", not to mention the time spent for refreshing package lists and calculating dependencies.

**Comment by lippserd** [comment]
Yeah, I get your point there. I thought that it is necessary to have those deps for coding assistance. But at least PhpStorm is smart enough to load this from the phars. I'll revert commit d63103cd198cf94acd3326261c05fa22cb47a165.

PHPUnit backported the namespace related changes to every version. Unfortunately only Xenial seems to have a version w/o those changes. I do not want to add the boilerplate compat stuff just for Xenial (in production w/o internet access) to every of our repos.

**Comment by Thomas-Gelf** [comment]
> Yeah, I get your point there. I thought that it is necessary to have those deps for coding assistance. But at least PhpStorm is smart enough to load this from the phars. I'll revert commit [d63103c](https://github.com/Icinga/ipl-stdlib/commit/d63103cd198cf94acd3326261c05fa22cb47a165).

:+1: 

> PHPUnit backported the namespace related changes to every version. Unfortunately only Xenial seems to have a version w/o those changes. I do not want to add the boilerplate compat stuff just for Xenial (in production w/o internet access) to every of our repos.

I didn't test others, did you? Stretch or so, any other Distro with 5.x? As far as I can recall, when we introduced these wrappers the main problem was that recent phpunit versions dropped support for PHP versions we had to support, and there was no namespace-based phpunit for them. So to support both, this wrapper has been introduced. I'd love to drop them in case they are obsolete right now!

**Comment by lippserd** [comment]
For Ubuntu xenial and trusty won't work for Debian it's just jessie. For RHEL 6 and 7 EPEL ships PHPUnit version 4.8.36 which has the namespaced TestCase. This "forward compatibility" exists in PHPUnit since 2016. That means every version after or equal to 4.8.35, 5.4, 6, 7, ...

**Pull request merged**
